name = "cellphonex-api"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[[d1_databases]]
binding = "DB"
database_name = "cellphonex-db"
database_id = "a6093079-830b-41e7-99dc-00f3d3dc5054"

[vars]
JWT_SECRET = "cellphonex-secret-key-2026"
FRONTEND_URL = "http://localhost:5173"
