INSERT INTO categories (id, name, slug) VALUES 
  (1, 'Điện thoại', 'dien-thoai'),
  (2, 'Laptop', 'laptop'),
  (3, 'Tablet', 'tablet'),
  (4, 'Phụ kiện', 'phu-kien'),
  (5, 'Đồng hồ', 'dong-ho');

INSERT INTO products (id, name, price, original_price, category_id, badge, chip, specs, description, image_url) VALUES 
  (1, 'iPhone 15 Pro Max', 28990000, 34990000, 1, 'Bán chạy', '⚡ A17 Pro 3nm', '["Camera 48MP 5X", "Khung Titan vũ trụ", "ProMotion 120Hz"]', 'iPhone 15 Pro Max là siêu phẩm đỉnh cao của Apple với thiết kế khung viền Titanium chuẩn hàng không vũ trụ, mang lại cảm giác cầm nắm siêu nhẹ nhưng vô cùng bền bỉ. Máy được trang bị chip A17 Pro tiến trình 3nm đầu tiên trên thế giới, tối ưu hóa sức mạnh chơi game đồ họa đỉnh cao với Ray Tracing chân thực. Hệ thống 3 camera sau đẳng cấp với cảm biến chính 48MP và camera Telephoto 5X zoom quang học xa nhất từ trước đến nay trên iPhone. Màn hình Super Retina XDR 6.7 inch sắc nét kết hợp công nghệ ProMotion 120Hz và Dynamic Island thông minh. Cổng sạc USB-C hỗ trợ truyền dữ liệu tốc độ cao chuẩn USB 3, cùng thời lượng pin bền bỉ suốt cả ngày dài.', 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80'),
  (2, 'Samsung Galaxy S24 Ultra', 25990000, 31990000, 1, 'Galaxy AI', '🚀 Snapdragon 8 Gen 3', '["Camera 200MP AI", "Bút S-Pen tích hợp", "Màn 2600 nits"]', 'Samsung Galaxy S24 Ultra mở ra kỷ nguyên quyền năng AI di động với bộ công cụ Galaxy AI đột phá: Khoanh vùng tìm kiếm đa năng (Circle to Search), dịch thuật cuộc gọi trực tiếp hai chiều, và trợ lý ghi chú thông minh. Thân máy chế tác từ khung Titanium sang trọng cùng kính cường lực Corning Gorilla Armor chống chói và chống trầy xước vượt trội. Sức mạnh bùng nổ nhờ vi xử lý Snapdragon 8 Gen 3 for Galaxy đỉnh cao cùng hệ thống tản nhiệt buồng hơi lớn hơn. Cụm camera 200MP bắt trọn chi tiết sắc nét ngay cả trong bóng đêm, zoom quang học 5x chuẩn quang học 10x. Bút S-Pen tích hợp mang đến trải nghiệm viết, vẽ và làm việc chuyên nghiệp mọi lúc mọi nơi.', 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80'),
  (3, 'MacBook Air M3', 27490000, 32490000, 2, 'Mới nhất', '✨ Apple M3 Chip', '["Pin bền 18 giờ", "Retina 13.6 inch", "Chỉ nặng 1.24kg"]', 'MacBook Air M3 sở hữu thiết kế siêu mỏng nhẹ thời thượng với độ dày chỉ 11.3mm và trọng lượng 1.24kg, hoàn hảo cho phong cách làm việc linh hoạt. Được trang bị chip Apple M3 tiến trình 3nm thế hệ mới, máy cho hiệu năng vượt trội trong cả tác vụ văn phòng lẫn chỉnh sửa đồ họa, video 4K. Màn hình Liquid Retina 13.6 inch hiển thị 1 tỷ màu rực rỡ, độ sáng 500 nits sống động. Máy hoạt động hoàn toàn yên tĩnh nhờ thiết kế không quạt tản nhiệt, thời lượng pin ấn tượng lên tới 18 giờ liên tục. Hỗ trợ xuất đồng thời 2 màn hình ngoài khi gập máy, kết nối Wi-Fi 6E siêu nhanh cùng cổng sạc từ tính MagSafe 3 tiện lợi và an toàn.', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80'),
  (4, 'iPad Pro M4', 23990000, 28990000, 3, 'Siêu mỏng', '🔮 Apple M4 OLED', '["Tandem OLED HDR", "Dày chỉ 5.1mm", "Apple Pencil Pro"]', 'iPad Pro M4 đánh dấu bước nhảy vọt công nghệ với độ mỏng kỷ lục chỉ 5.1mm – thiết bị mỏng nhất từ trước đến nay của Apple. Sức mạnh vượt trội đến từ chip Apple M4 thế hệ kế tiếp, sở hữu Neural Engine mạnh mẽ tối ưu tối đa cho các tác vụ trí tuệ nhân tạo chuyên sâu. Màn hình Ultra Retina XDR đột phá sử dụng công nghệ Tandem OLED hai lớp, mang đến độ sáng toàn màn hình 1000 nits và cực đại 1600 nits cho nội dung HDR chân thực đến từng chi tiết. Thiết bị tương thích hoàn hảo với bút Apple Pencil Pro mới hỗ trợ cử chỉ bóp, xoay thân bút và bàn phím Magic Keyboard mỏng nhẹ hơn.', 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop&q=80'),
  (5, 'AirPods Pro 2', 5690000, 6790000, 4, 'Âm thanh Pro', '🎧 Apple H2 Audio', '["Chống ồn ANC 2X", "Adaptive Sound", "Cổng USB-C"]', 'AirPods Pro 2 (phiên bản cổng sạc USB-C) mang đến trải nghiệm âm thanh cao cấp với chip xử lý âm thanh Apple H2 tiên tiến. Công nghệ Chủ động khử tiếng ồn (ANC) mạnh gấp 2 lần thế hệ trước, giúp bạn hoàn toàn đắm chìm trong không gian âm nhạc riêng biệt. Tính năng Âm thanh thích ứng (Adaptive Audio) tự động điều chỉnh mức khử ồn theo môi trường xung quanh, cùng Chế độ Nhận biết cuộc trò chuyện tự động giảm âm lượng khi bạn bắt đầu nói chuyện. Hộp sạc MagSafe trang bị loa tìm kiếm, chip định vị U1 và chuẩn kháng bụi/nước IP54 bền bỉ, thời lượng nghe nhạc lên đến 6 giờ (30 giờ khi kèm hộp sạc).', 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&auto=format&fit=crop&q=80'),
  (6, 'Apple Watch Ultra 2', 18990000, 21990000, 5, 'Đỉnh cao', '🧭 Dual-GPS L1/L5', '["Vỏ Titan 49mm", "Màn hình 3000 nits", "Pin tới 72 giờ"]', 'Apple Watch Ultra 2 là người bạn đồng hành tối thượng dành cho thể thao mạo hiểm và khám phá địa hình. Sở hữu khung vỏ Titanium 49mm chống va đập tiêu chuẩn quân đội và mặt kính Sapphire cao cấp. Màn hình Always-On đạt độ sáng cực đại 3000 nits, hiển thị rõ ràng ngay cả dưới ánh nắng chói chang nhất. Được trang bị chip S9 SiP mạnh mẽ với tính năng cử chỉ Chạm hai lần (Double Tap) kỳ diệu mà không cần chạm vào màn hình. Hệ thống GPS tần số kép L1 và L5 mang lại độ chính xác định vị hàng đầu thế giới. Khả năng kháng nước ở độ sâu lên đến 100 mét, chuẩn lặn EN13319 và thời lượng pin ấn tượng từ 36 đến 72 giờ ở chế độ tiết kiệm năng lượng.', 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80');

INSERT INTO admin_users (username, password_hash) VALUES 
  ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9');
